
server_tokens off;
access_log /var/log/nginx/access.log;
error_log /var/log/nginx/error.log;

server {
    listen 443 ssl;
    ssl_certificate /home/ubuntu/SightPath/sightpath.tw.origincert.pem;
    ssl_certificate_key /home/ubuntu/SightPath/sightpath.tw.privatekey.pem;

    server_name sightpath.tw;
    # listen 80;

    location / {
        include proxy_params;
        proxy_pass http://127.0.0.1:8000;
    }

    location /static/admin/ {
        autoindex on;
        root /usr/local/lib/python3.10/dist-packages/django/contrib/admin/;
    }

    location /static/ {
        autoindex on;
        root /home/ubuntu/SightPath/;
    }
}