# Generated by Django 4.2.1 on 2024-06-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
