# Generated by Django 4.2.1 on 2023-11-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="eventPlaceType",
            field=models.TextField(null=True),
        ),
    ]
