# Generated by Django 4.2.1 on 2023-11-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room", name="pin", field=models.BooleanField(default=False),
        ),
    ]
