# Generated by Django 4.2.1 on 2023-11-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="line_user_id",
            field=models.CharField(blank=True, default="", max_length=80, null=True),
        ),
    ]
