# Generated by Django 4.2.1 on 2023-11-21 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_room_like"),
    ]

    operations = [
        migrations.RemoveField(model_name="room", name="like",),
        migrations.AddField(
            model_name="room",
            name="likes",
            field=models.ManyToManyField(
                default=0, related_name="likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
