# Generated by Django 4.2.1 on 2023-10-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_user_bio_alter_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                default="使用者<property object at 0x0000015C0A317EF0>", max_length=20
            ),
        ),
    ]
