# Generated by Django 4.2.1 on 2024-06-17 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_activity_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity", old_name="agency_title", new_name="organizer",
        ),
        migrations.RemoveField(model_name="activity", name="guide_line_html",),
    ]
