# Generated by Django 4.2.1 on 2023-10-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                default="使用者<django.db.models.fields.AutoField>", max_length=20
            ),
        ),
    ]
