# Generated by Django 4.2.1 on 2023-11-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_pin_room_pin_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourtag',
            name='emb',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
