# Generated by Django 4.2.1 on 2023-07-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="avatar.png", null=True, upload_to=""),
        ),
    ]
