# Generated by Django 4.2.1 on 2023-07-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_user_avatar"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="name",),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
