# Generated by Django 4.2.1 on 2023-07-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_remove_user_name_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="agency_title",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="competition",
            name="contact_email",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="competition",
            name="contact_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="competition",
            name="contact_phone",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="competition",
            name="cover_img",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="competition",
            name="create_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="competition",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="competition",
            name="page_views",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="competition", name="href", field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="competition", name="name", field=models.TextField(),
        ),
    ]
