# Generated by Django 4.2.1 on 2023-07-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_competition_agency_title_competition_contact_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name="competition", old_name="create_time", new_name="start_time",
        ),
        migrations.RemoveField(model_name="competition", name="cover_img",),
        migrations.AddField(
            model_name="competition",
            name="cover_img_url",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="competition",
            name="tags",
            field=models.ManyToManyField(blank=True, to="base.competitiontag"),
        ),
    ]
