# Generated by Django 4.2.1 on 2023-07-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_competitiontag_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="competition", name="href",),
        migrations.AddField(
            model_name="competition",
            name="limit_highschool",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="competition",
            name="limit_none",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="competition",
            name="limit_other",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="competition", name="url", field=models.URLField(null=True),
        ),
    ]
