# Generated by Django 4.2.1 on 2023-07-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_remove_competition_href_competition_limit_highschool_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="contact_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="competition",
            name="cover_img_url",
            field=models.URLField(null=True),
        ),
    ]
