# Generated by Django 4.2.1 on 2023-07-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_competition_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="guide_line_html",
            field=models.TextField(null=True),
        ),
    ]
