# Generated by Django 4.2.1 on 2023-07-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_competition_guide_line_html"),
    ]

    operations = [
        migrations.RenameField(
            model_name="competition",
            old_name="agency_title",
            new_name="organizer_title",
        ),
    ]
