# Generated by Django 4.2.1 on 2023-09-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_agency_title_competition_organizer_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
