# Generated by Django 4.2.1 on 2023-10-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_competition_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('eventIdNumber', models.TextField(null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('eventPlaceType', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('isAD', models.BooleanField(null=True)),
                ('photoUrl', models.URLField(null=True)),
                ('strtags', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='competition',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
